### ISSUE TITLE
Refactor to fix dialog progression

### ISSUE THREAD

**Issue by jonuy** [DoSomethingGames/words-that-matter#1]
So currently, with the `for` loop in the `create` function, it's actually just looping through the entire progression at once and all you catch is the end dialog. There's probably several ways to approach this problem, but the gist of it is to stall dialog progression until either 1) some set amount of time passes or 2) the user makes a choice.

Here's one possible suggestion with comments as pseudocode:

Instead of the block of code you have in the `create` right now, place a function like `displayNext()` in there. Then `displayNext()` could be something like...

```
var dialogueTree = [0, 'date', 'friend', 1, 'date', 'friend', 'date', 2, 'friend', 'date', 3, 'date', 4];
var progress = 0;
function displayNext() {
  // destroy any existing dialogue sprite that's currently open

  if (dialogueTree[progress] typeof === 'number') {
    // create buttons and show choices for dialogue progress 0

    // set listener for button clicks
    choiceButton1.onInputUp(onChoiceUp, {button: choiceButton1});
    choiceButton2.onInputUp(onChoiceUp, {button: choiceButton2});
  }
  else if (dialogueTree[progress] == 'date') {
    // show date dialogue

    // move onto next dialogue after some set time
    setTimeout(displayNext, DATE_DIALOGUE_DISPLAY_TIME);

    // Note: if we wanted dialogue to overlap at some points, we could set different logic for when dialogue
    // gets destroyed and when it gets created
  }
  else if (dialogueTree[progress] == 'friend') {
    // show friend dialogue

    // move onto next dialogue after some set time
    setTimeout(displayNext, FRIEND_DIALOGUE_DISPLAY_TIME);
  }

  progress++;
}

function onChoiceUp() {
  // determine which button just got clicked by checking this.button
  // log the selection

  // progress to the next dialog item
  displayNext();
}
```

Other suggestions:
- I imagine there could be scenarios where you'll want to have more control over the time delay between dialogue showing up. So instead of numbers or strings in the `dialogueTree` variable, you could place objects with a known structure. ex:

```
var dialogueTree = [
  {type: 'choice', msg: 0},
  {type: 'date', msg: 0},
  {type: 'friend', msg: 0},
  {type: 'choice', msg: 1}, ...
];
```

I'm not sure if that's the best way, but it's a thought, and I like being explicit with data structures so other coders have a better idea of how to interpret it.

I'm sure there's probably questions, so feel free to drop them in here and @ mention me, and/or let's find time to go into more detail offline tomorrow.

**Comment by jmithani** [comment]
Completed.
