### ISSUE TITLE
Transition between GR and AP states

### ISSUE THREAD

**Issue by jmithani** [DoSomethingGames/words-that-matter#16]
The transition between the two is choppy. Tween into the AP from the GR, and then add this further down the road with AP -> minigame and minigame -> BI.

@jonuy would you be up to this? Because you did the tweening for the other ones. I tried it and got some errors with the dialogue, but can work on it if you're busy today.

**Comment by jonuy** [comment]
Yea, this one's been on my mind for a while. If I don't fix this today. Come yell at me tomorrow.

related: #10
